- name: Touch a file, using symbolic modes to set the permissions (equivalent to 0644)
  ansible.builtin.file:
    path: /etc/id_rsa.pub
    state: touch
    mode: u=rw,g=r,o=r

- name: Copy authorized key from env to file.
  copy:
    dest: /etc/id_rsa.pub
    content: "{{ ssh_key }}"

- ansible.builtin.debug:
    msg: "{{ lookup('ansible.builtin.file', '/etc/id_rsa.pub') }}"

- name: Set authorized key for remote user.
  authorized_key:
    user:  admin
    state: present
    key: "{{ lookup('file', '/etc/id_rsa.pub') }}"