- name: ensure file exists
  copy:
    content: "{{ ssh_key }}"
    dest: /etc/id_rsa
    force: no
    group: sys
    owner: admin
    mode: 0555

- name: Set authorized key for remote user.
  authorized_key:
    user:  admin
    state: present
    key: "{{ lookup('file', '/etc/id_rsa') }}"