import os

TEST_SERVER_DB_PASSWORD = os.environ.get('TEST_SERVER_DB_PASSWORD')
print(TEST_SERVER_DB_PASSWORD)
# MYSQL Series
SQLALCHEMY_DATABASE_URL = f"mysql+pymysql://admin:{TEST_SERVER_DB_PASSWORD}@127.0.0.1:3306/students"

print(SQLALCHEMY_DATABASE_URL)
