---
mysql_user_home: /root
mysql_user_name: root
mysql_user_password: root
mysql_root_home: /root
mysql_root_username: root
mysql_root_password: root
mysql_root_password_update: false
mysql_user_password_update: false
mysql_enabled_on_startup: true
overwrite_global_mycnf: true
mysql_enablerepo: ""
mysql_python_package_debian: python3-mysqldb
mysql_port: "3306"
mysql_bind_address: '0.0.0.0'
mysql_skip_name_resolve: false
mysql_datadir: /var/lib/mysql
mysql_sql_mode: ~
mysql_log_file_group: mysql
mysql_slow_query_log_enabled: false
mysql_slow_query_time: "2"
mysql_key_buffer_size: "256M"
mysql_max_allowed_packet: "64M"
mysql_table_open_cache: "256"
mysql_sort_buffer_size: "1M"
mysql_read_buffer_size: "1M"
mysql_read_rnd_buffer_size: "4M"
mysql_myisam_sort_buffer_size: "64M"
mysql_thread_cache_size: "8"
mysql_query_cache_type: "0"
mysql_query_cache_size: "16M"
mysql_query_cache_limit: "1M"
mysql_max_connections: "151"
mysql_tmp_table_size: "16M"
mysql_max_heap_table_size: "16M"
mysql_group_concat_max_len: "1024"
mysql_join_buffer_size: "262144"
mysql_lower_case_table_names: "0"
mysql_wait_timeout: "28800"
mysql_event_scheduler_state: "OFF"
mysql_innodb_file_per_table: "1"
mysql_innodb_buffer_pool_size: "256M"
mysql_innodb_log_file_size: "64M"
mysql_innodb_log_buffer_size: "8M"
mysql_innodb_flush_log_at_trx_commit: "1"
mysql_innodb_lock_wait_timeout: "50"
mysql_innodb_large_prefix: "1"
mysql_innodb_file_format: "barracuda"
mysql_mysqldump_max_allowed_packet: "64M"
mysql_log: ""
mysql_config_include_files: []
mysql_databases: []
mysql_users: []
mysql_disable_log_bin: false
mysql_server_id: "1"
mysql_max_binlog_size: "100M"
mysql_binlog_format: "ROW"
mysql_expire_logs_days: "10"
mysql_replication_role: ''
mysql_replication_master: ''
mysql_replication_user: []