mysql_root_password: "{{ db_password }}"
mysql_databases:
  - name: students
    collation: utf8_general_ci
    encoding: utf8

mysql_users:
  - name: teacher
    host: "172.20.0.2"
    password: "{{ db_password }}"
    priv: "*.*:ALL"
  - name: admin
    host: localhost"
    password: "{{ db_password }}"
    priv: "*.*:ALL"