name: Deploying frontend

on:
  workflow_dispatch:
  push:
    paths:
      - 'frontend/**'

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Downcase repository owner
        run: |
          echo "OWNER=${GITHUB_REPOSITORY_OWNER,,}" >>${GITHUB_ENV}
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:frontend"
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ghcr.io/${{ env.OWNER }}/students_frontend:latest

      - name: Run
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.TEST_SERVER_HOST }}
          username: admin
          key: ${{ secrets.TEST_SERVER_PRIVATE_KEY }}
          port: 2202
          script: |
            export CR_PAT=${{ secrets.GITHUB_TOKEN }}
            echo $CR_PAT | docker login ghcr.io -u ${{ env.OWNER }} --password-stdin
            docker stop $(docker ps -a -q --filter ancestor=ghcr.io/${{ env.OWNER }}/students_frontend:latest --format="{{.ID}}")
            docker rmi $(docker images -q)
            docker run -d --rm -p 80:80 ghcr.io/${{ env.OWNER }}/students_frontend:latest