name: MySQL dump

on:
  workflow_dispatch:

env:
  TEST_SERVER_DB_PASSWORD: ${{ secrets.TEST_SERVER_DB_PASSWORD }}

jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
      - name: Run
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.TEST_SERVER_HOST }}
          username: admin
          key: ${{ secrets.TEST_SERVER_PRIVATE_KEY }}
          port: 2202
          envs: TEST_SERVER_DB_PASSWORD
          script: mysqldump -u admin -p$TEST_SERVER_DB_PASSWORD students > dump.sql


