name: MySQL dump

on:
  workflow_dispatch:

jobs:
  build-and-push-docker-images:
    runs-on: ubuntu-latest
    steps:
      - name: Setup test database
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql version: '8.0'
          mysql database: 'students'
          mysql root password: ${{ secrets.TEST_SERVER_DB_PASSWORD }}
          mysql user: 'teacher'
          mysql password: ${{ secrets.TEST_SERVER_DB_PASSWORD }}
        run: mysqldump students > dump.sql