name: Setting up the server

on:
  workflow_dispatch:

env:
  TEST_SERVER_PRIVATE_KEY: ${{ secrets.TEST_SERVER_PRIVATE_KEY }}
  TEST_SERVER_PUBLIC_KEY: ${{ secrets.TEST_SERVER_PUBLIC_KEY }}
  TEST_SERVER_USER: ${{ secrets.TEST_SERVER_USER }}
  TEST_SERVER_LOGIN: ${{ secrets.TEST_SERVER_LOGIN }}
  TEST_SERVER_PASSWORD: ${{ secrets.TEST_SERVER_PASSWORD }}
  TEST_SERVER_HOST: ${{ secrets.TEST_SERVER_HOST }}
  TEST_SERVER_DB_PASSWORD: ${{ secrets.TEST_SERVER_DB_PASSWORD }}

jobs:
  setup-runner:
    runs-on: ubuntu-latest
    steps:

      - name: Install ansible
        run: |
          sudo apt install software-properties-common
          sudo add-apt-repository --yes --update ppa:ansible/ansible
          sudo apt install ansible
          sudo apt-get install sshpass

      - name: Checkout
        uses: actions/checkout@v3

      - name: Creating id_rsa
        run: |
          cd devops/
          echo ${{ secrets.TEST_SERVER_PUBLIC_KEY }} > id_rsa

      - name: Ansible. Installing Docker, MySQL and SSH
        run: |
          sudo ansible-playbook playbook.yml -e "\
          ansible_host=${TEST_SERVER_HOST} \
          ansible_ssh_user=${TEST_SERVER_LOGIN} \
          ansible_ssh_pass=${TEST_SERVER_PASSWORD} \
          db_password=${TEST_SERVER_DB_PASSWORD}"
        working-directory: ./devops
