name: Start server

on:
  workflow_dispatch:

env:
  TEST_SERVER_DB_PASSWORD: ${{ secrets.TEST_SERVER_DB_PASSWORD }}
  TEST_SERVER_HOST: ${{ secrets.TEST_SERVER_HOST }}

jobs:
  build-and-push-docker-images:
    runs-on: ubuntu-latest
    steps:
      - name: Downcase repository owner
        run: |
          echo "OWNER=${GITHUB_REPOSITORY_OWNER,,}" >>${GITHUB_ENV}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push frontend
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:frontend"
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ghcr.io/${{ env.OWNER }}/students_frontend:latest

      - name: Build and push backend
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:backend"
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ghcr.io/${{ env.OWNER }}/students_backend:latest

  run-docker-images:
    needs: build-and-push-docker-images
    runs-on: ubuntu-latest
    steps:
      - name: Run
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.TEST_SERVER_HOST }}
          username: admin
          key: ${{ secrets.TEST_SERVER_PRIVATE_KEY }}
          port: 2202
          envs: TEST_SERVER_HOST,TEST_SERVER_DB_PASSWORD
          script: |
            docker network create --subnet=172.20.0.0/16 studentsnet
            rm .env
            echo TEST_SERVER_HOST=host.docker.internal >> .env
            echo TEST_SERVER_DB_PASSWORD=$TEST_SERVER_DB_PASSWORD >> .env
            echo TEST_SERVER_IP=$TEST_SERVER_HOST >> .env
            export CR_PAT=${{ secrets.GITHUB_TOKEN }}
            echo $CR_PAT | docker login ghcr.io -u ${{ env.OWNER }} --password-stdin
            docker run --net studentsnet --ip 172.20.0.2 --env-file ./.env --add-host=host.docker.internal:host-gateway -d --rm -p 8080:8080 ghcr.io/${{ env.OWNER }}/students_backend:latest
            docker run -d --rm -p 80:80 ghcr.io/${{ env.OWNER }}/students_frontend:latest