name: Testing env

on:
  workflow_dispatch:

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Run
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.TEST_SERVER_HOST }}
          username: admin
          key: ${{ secrets.TEST_SERVER_PRIVATE_KEY }}
          port: 2202
          script: |
            rm new.txt
            echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
            echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
            echo ${{ github.repository_owner }} >> new.txt
            echo ${OWNER_LC} >> new.txt
            echo ${REPO} >> new.txt
