name: Testing env

on:
  workflow_dispatch:

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: downcase REPO
        run: |
          echo "REPO=${GITHUB_REPOSITORY_OWNER,,}" >>${GITHUB_ENV}
      - name: Run
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.TEST_SERVER_HOST }}
          username: admin
          key: ${{ secrets.TEST_SERVER_PRIVATE_KEY }}
          port: 2202
          script: |
            rm new.txt
            echo ${{ env.REPO }} >> new.txt

